version: '3.3'

services:
        webapp:
         build: 
                context: .
                dockerfile: Dockerfile
         ports:
                 - 3000:5000
         image: wepapplication:latest
         depends_on:
                 - mysql_server

        mysql_server:
         build:
                 context: .
                 dockerfile: Dockerfile2
         command: --default-authentication-plugin=mysql_native_password
         container_name: mysql_server
         networks:
                 default:
                         aliases:
                                 - mysql_server
         environment:
                 MYSQL_ROOT_PASSWORD: 'lokesh1999'
         ports:
                - 3306:3306
